package mx.com.teclo.saicdmx.util.enumerados;

public enum ArchivoBatchEstatusEnum {

	// Codigos de error
	 WS_REQUEST_OK  (0), 
	 WS_NO_SE_PUEDE_OBTENER_ARCHIVO (1),
	WS_NO_EXISTE_ARCHIVO ( 2),
	 WS_FALLO_INICIAR_PROCESO ( 3),
	 WS_ERROR_CALCULAR_RUTA_ARCHIVO  (4),
	 WS_FALLO_INICIAR_ENTREGA  (5),
	 WS_FALLO_ENTREGA_ARCHIVO  (6),
	 WS_REQUEST_FAILED (50),
	// Codigos de estatus
	 WS_ARCHIVO_PROCESADO_SIN_ERRORES (100),
	 WS_ARCHIVO_PROCESADO_CON_ERRORES  (101),
	 WS_ARCHIVO_EN_PROCESO  (29),
	// Estatus de la complementación
	 INVALIDO ( 0),
	 ARCHIVO_LISTO_PARA_COMPLEMENTAR  (1),
	 VALIDANDO_REGISTROS_DUPLICADOS (2),
	 REGISTROS_DUPLICADOS_VALIDADOS  (3),
	 COMPLEMENTANDO_INFORMACION_SETRAVI ( 4),
	 INFORMACION_SETRAVI_COMPLEMENTADA_PARCIALMENTE (5),
	 INFORMACION_SETRAVI_COMPLEMENTADA  (6),
	 COMPLEMENTANDO_CENTRO_REPARTO ( 7),
	 CENTRO_REPARTO_COMPLEMENTADO (8),
     RECOMPLEMENTANDO_CENTRO_REPARTO (9),
	 REASIGNANDO_CODIGO_POSTAL (10),
	 CODIGO_POSTAL_REASIGNADO  (11),
	 GENERANDO_FOLIOS_INFRACCION (12),
	 FOLIOS_INFRACCION_GENERADOS (13),
	 GENERANDO_ARCHIVO_INFRACCIONES (14),
	 ARCHIVO_INFRACCIONES_GENERADO (15),
	 ENVIANDO_ARCHIVO_INFRACCIONES (16),
	 ARCHIVO_INFRACCIONES_ENVIADO  (17),
	 ERROR_ENVIANDO_ARCHIVO_INFRACCIONES (18),
	 ASIGNANDO_LC_ARCHIVO_INFRACCIONES  (19),
	 LC_ASIGNADA_ARCHIVO_INFRACCIONES  (20),
	 ERROR_ASIGNANDO_LC_ARCHIVO_INFRACCIONES (21),
	 RECUPERANDO_ARCHIVO_INFRACCIONES  (22),
	 ARCHIVO_INFRACCIONES_RECUPERADO  (23),
	 ERROR_RECUPERANDO_ARCHIVO_INFRACCIONES  (24),
	 CARGANDO_ARCHIVO_INFRACCIONES  (25),
	 ARCHIVO_INFRACCIONES_CARGADO  (26),
	 COMPLEMENTANDO_UT  (27),
	 UT_COMPLEMENTADA (28),
	 ARCHIVO_COMPLEMENTADO (29),
	 ARCHIVO_LISTO_PARA_LIBERAR (30),
	 LIBERANDO_INFRACCIONES_RADAR (31),
	 INFRACCIONES_RADAR_LIBERADAS (32),
	 PROCESO_CANCELADO  (33),
	 
	 REGISTRO_ACTIVO  (1),
	 REGISTRO_INACTIVO  (0),
	 REGISTRO_DUPLICADO  (1),
	 REGISTRO_NODUPLICADO  (0);
//	private  String NODO_OPCIONAL = " ";
	// La clave de pago es constante
//	private  String CLAVE_PAGO = "49";
//	private  String NOMBRE_CLASE = "ArchivoBatchFinanzas";
//	private  int PROCESO_NOMBRE_ARCHIVO_NOCREADO = 1;
//	private  int PROCESO_NOMBRE_ARCHIVO_ENCURSO = 2;
	
	private Integer estatusProceso;
	
	private ArchivoBatchEstatusEnum(Integer estatusProceso) {
		this.setEstatusProceso(estatusProceso);
	}

	public Integer getEstatusProceso() {
		return estatusProceso;
	}

	public void setEstatusProceso(Integer estatusProceso) {
		this.estatusProceso = estatusProceso;
	}
	
	
	public static EstatusProcesoLote getArchivoEstatusProceso(Integer x) {
		for (EstatusProcesoLote currentType : EstatusProcesoLote.values()) {
	      if (x.equals(currentType.getEstatusProceso())) {
	        return currentType;
	      }
	    }
	    return null;
	  }
}
