package mx.com.teclo.saicdmx.persistencia.mybatis.dao.radararchivodetallehist;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface RadarArchivoDetalleHistMyBatisDAO {
	
	String INSERT_RADAR_ARCHIVO_DETALLE_CANCELACION = 
			"INSERT INTO RADAR_ARCHIVO_DETALLE_HIST( "+
			"	ID,RADAR_ARCHIVO_ID,PLACA,FECHA,HORA,TDSKUID,UT,VELOCIDAD_DETECTADA,FECHA_CREACION,PLACA_SF,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,"+
			"	CALLE,NUM_EXTERIOR,NUM_INTERIOR,COLONIA,MUNICIPIO,CODIGO_POSTAL,ENTIDAD_FEDERATIVA,MARCA,SUBMARCA,MODELO,TELEFONO,SERIE,MOTOR,"+
			"	WS_SETRAVI_CONSULTADO,ERROR_WS_SETRAVI,FECHA_CONSULTA_WS_SETRAVI,CENTRO_REPARTO,CP_MODIFICADO_POR,FECHA_CP_MODIFICADO,INFRAC_NUM,"+
			"	DIAS,PORCENTAJE_DESCUENTO,FECHA_IMPOSICION,FECHA_VENCIMIENTO,IMPORTE_DESCUENTO,IMPORTE_INFRACCION,IMPORTE_DERECHOS,IMPORTE_ACTUALIZACION,"+
			"	IMPORTE_RECARGOS,IMPORTE_CEROS,IMPORTE_TOTAL,LINEA_CAPTURA,CLAVE_PAGO,COMPLEMENTADO_LC,FECHA_COMPLEMENTADO_LC,UT_CALLE,UT_ENTRE_CALLE,"+
			"	UT_Y_CALLE,UT_SECTOR,UT_DELEGACION,UT_COLONIA,UT_SECTOR_ID,UT_DELEGACION_ID,COMPLEMENTADO_UT,FECHA_COMPLEMENTADO_UT,COMPLEMENTADO,FECHA_COMPLEMENTADO,"+
			"	ACTIVO,DUPLICADO,SIN_DATOS_SETRAVI,SIN_CENTRO_REPARTO,SIN_LC,SIN_UT,PROCESO_CANCELADO,ART_ID,OFICIAL_PLACA,OFICIAL_NOMBRE,LIBERADO,FECHA_LIBERADO, ART_NUMERO, ART_FRACCION, ART_PARRAFO, ART_INCISO, ART_UNIDAD_CUENTA) "+
			"SELECT	ID,RADAR_ARCHIVO_ID,PLACA,FECHA,HORA,TDSKUID,UT,VELOCIDAD_DETECTADA,FECHA_CREACION,PLACA_SF,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,"+
			"		CALLE,NUM_EXTERIOR,NUM_INTERIOR,COLONIA,MUNICIPIO,CODIGO_POSTAL,ENTIDAD_FEDERATIVA,MARCA,SUBMARCA,MODELO,TELEFONO,SERIE,MOTOR,"+
			"		WS_SETRAVI_CONSULTADO,ERROR_WS_SETRAVI,FECHA_CONSULTA_WS_SETRAVI,CENTRO_REPARTO,CP_MODIFICADO_POR,FECHA_CP_MODIFICADO,INFRAC_NUM,"+
			"		DIAS,PORCENTAJE_DESCUENTO,FECHA_IMPOSICION,FECHA_VENCIMIENTO,IMPORTE_DESCUENTO,IMPORTE_INFRACCION,IMPORTE_DERECHOS,IMPORTE_ACTUALIZACION,"+
			"		IMPORTE_RECARGOS,IMPORTE_CEROS,IMPORTE_TOTAL,LINEA_CAPTURA,CLAVE_PAGO,COMPLEMENTADO_LC,FECHA_COMPLEMENTADO_LC,UT_CALLE,UT_ENTRE_CALLE,"+
			"		UT_Y_CALLE,UT_SECTOR,UT_DELEGACION, UT_COLONIA,UT_SECTOR_ID,UT_DELEGACION_ID,COMPLEMENTADO_UT,FECHA_COMPLEMENTADO_UT,COMPLEMENTADO,FECHA_COMPLEMENTADO,"+
			"		ACTIVO,DUPLICADO,SIN_DATOS_SETRAVI,SIN_CENTRO_REPARTO,SIN_LC,SIN_UT,PROCESO_CANCELADO,ART_ID,OFICIAL_PLACA,OFICIAL_NOMBRE,LIBERADO,FECHA_LIBERADO, ART_NUMERO, ART_FRACCION, ART_PARRAFO, ART_INCISO, ART_UNIDAD_CUENTA "+
			"FROM	RADAR_ARCHIVO_DETALLE "+
			"WHERE 	RADAR_ARCHIVO_ID = #{radarArchivoId}";
	
	@Insert(INSERT_RADAR_ARCHIVO_DETALLE_CANCELACION)
	public Integer insertaRadarArchivoDetalleCompleto(@Param("radarArchivoId") Long radarArchivoId);
}
