package mx.com.teclo.saicdmx.persistencia.mybatis.dao.impugnacion;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import mx.com.teclo.saicdmx.persistencia.vo.impugnacion.InfraccionConsultaVO;
/**
 * 
 * @author javier07
 *
 */
@Mapper
public interface ImpugnacionInfracMyBatisDAO {

	 String T_INFRACIONES_CONSULTA = " SELECT NCI, ESTATUS, INFRACCION, INFRACCION_IMPRESA, ESTADO, SECTOR, UNIDAD_TERRITORIAL, APE_PATERNO, APE_MATERNO, NOMBRE, CALLE, NUM_EXTERIOR, NUM_INTERIOR, COLONIA, DELEGACION, EDO_INFRACTOR, LICENCIA,TIPO_LICENCIA, LIC_EXPEDIDA_EN, VEHICULO_TIPO, ORIGEN, MARCA, MODELO, COLOR, SERVICIO_PUBLICO, CON_PLACA,PLACA, PLACA_EXPEDIDA_EN, TARJETA_CIRCULACION, EN_LA_CALLE, ENTRE_LA_CALLE, Y_LA_CALLE, FECHA_INFRACCION,COLONIA_INFRACCION, DELEGACION_INFRACCION, ARTICULO, FRACCION, PARRAFO, INCISO, LEY_TRANSPORTE, MOTIVACION,DIAS_SAL_MIN, ART_SANCION, EVENTO_INFRACCION, EVENTO_INMOVILIZACION, EVENTO_LEVANTAMIENTO, EVENTO_ARRASTRE ,TIPO_ARRASTRE, NUMERO_ARRASTRE, NUMERO_GRUA, DEPOSITO, EMPLEADO, EMP_SECTOR, EMP_PLACA, EMP_AGRUPAMIENTO,EMP_RESPONSABLE, INFRACTOR, FUNDAMENTACION, MONTO, REDUCCION , ACTUALIZACION , RECARGOS, DERECHO_PISO , ARRASTRE,TOTAL, DEPO_NOMBRE, DEPO_DIRECCION , DEPO_COLONIA, DEPO_DELEGACION, DEPO_TELEFONO FROM TABLE ( CAST ( " +
				" Fn_infraccion_consulta_prueba(#{valor}) AS T_INFRACIONES_CONSULTA)) union " +
				" SELECT NCI, ESTATUS, INFRACCION, INFRACCION_IMPRESA, ESTADO, SECTOR, UNIDAD_TERRITORIAL, APE_PATERNO, APE_MATERNO, NOMBRE, CALLE, NUM_EXTERIOR, NUM_INTERIOR, COLONIA, DELEGACION, EDO_INFRACTOR, LICENCIA,TIPO_LICENCIA, LIC_EXPEDIDA_EN, VEHICULO_TIPO, ORIGEN, MARCA, MODELO, COLOR, SERVICIO_PUBLICO, CON_PLACA,PLACA, PLACA_EXPEDIDA_EN, TARJETA_CIRCULACION, EN_LA_CALLE, ENTRE_LA_CALLE, Y_LA_CALLE, FECHA_INFRACCION,COLONIA_INFRACCION, DELEGACION_INFRACCION, ARTICULO, FRACCION, PARRAFO, INCISO, LEY_TRANSPORTE, MOTIVACION,DIAS_SAL_MIN, ART_SANCION, EVENTO_INFRACCION, EVENTO_INMOVILIZACION, EVENTO_LEVANTAMIENTO, EVENTO_ARRASTRE ,TIPO_ARRASTRE, NUMERO_ARRASTRE, NUMERO_GRUA, DEPOSITO, EMPLEADO, EMP_SECTOR, EMP_PLACA, EMP_AGRUPAMIENTO,EMP_RESPONSABLE, INFRACTOR, FUNDAMENTACION, MONTO, REDUCCION , ACTUALIZACION , RECARGOS, DERECHO_PISO , ARRASTRE,TOTAL, DEPO_NOMBRE, DEPO_DIRECCION , DEPO_COLONIA, DEPO_DELEGACION, DEPO_TELEFONO FROM TABLE ( CAST ( " +
			    " Fn_infraccion_consulta_dig_pru(#{valor}) AS T_INFRACIONES_CONSULTA)) union " +
				" SELECT NCI, ESTATUS, INFRACCION, INFRACCION_IMPRESA, ESTADO, SECTOR, UNIDAD_TERRITORIAL, APE_PATERNO, APE_MATERNO, NOMBRE, CALLE, NUM_EXTERIOR, NUM_INTERIOR, COLONIA, DELEGACION, EDO_INFRACTOR, LICENCIA,TIPO_LICENCIA, LIC_EXPEDIDA_EN, VEHICULO_TIPO, ORIGEN, MARCA, MODELO, COLOR, SERVICIO_PUBLICO, CON_PLACA,PLACA, PLACA_EXPEDIDA_EN, TARJETA_CIRCULACION, EN_LA_CALLE, ENTRE_LA_CALLE, Y_LA_CALLE, FECHA_INFRACCION,COLONIA_INFRACCION, DELEGACION_INFRACCION, ARTICULO, FRACCION, PARRAFO, INCISO, LEY_TRANSPORTE, MOTIVACION,DIAS_SAL_MIN, ART_SANCION, EVENTO_INFRACCION, EVENTO_INMOVILIZACION, EVENTO_LEVANTAMIENTO, EVENTO_ARRASTRE ,TIPO_ARRASTRE, NUMERO_ARRASTRE, NUMERO_GRUA, DEPOSITO, EMPLEADO, EMP_SECTOR, EMP_PLACA, EMP_AGRUPAMIENTO,EMP_RESPONSABLE, INFRACTOR, FUNDAMENTACION, MONTO, REDUCCION , ACTUALIZACION , RECARGOS, DERECHO_PISO , ARRASTRE,TOTAL, DEPO_NOMBRE, DEPO_DIRECCION , DEPO_COLONIA, DEPO_DELEGACION, DEPO_TELEFONO FROM TABLE ( CAST ( " +
			    " Fn_infraccion_consulta_radar(#{valor}) AS T_INFRACIONES_CONSULTA))";

	
	@Select(T_INFRACIONES_CONSULTA)
	public List<InfraccionConsultaVO> obtieneInfraccionImpugna(@Param("valor") String valor);



}
